Repository FuelLabs/bridge-fungible-token, pull requests merged in 2022-11, with the labels that each got.

#28 Add the `BridgeFungibleToken` contract
  .github/scripts/test.sh
  .github/workflows/ci.yml
  bridge-fungible-token-abi/Forc.lock
  bridge-fungible-token-abi/Forc.toml
  bridge-fungible-token-abi/src/bridge_fungible_token_abi.sw
  bridge-fungible-token-abi/src/lib.sw
  bridge-fungible-token/Cargo.lock
  bridge-fungible-token/Cargo.toml
  bridge-fungible-token/Forc.lock
  bridge-fungible-token/Forc.toml
  bridge-fungible-token/src/bridge_fungible_token.sw
  bridge-fungible-token/src/data.sw
  bridge-fungible-token/src/errors.sw
  bridge-fungible-token/src/events.sw
  bridge-fungible-token/src/main.sw
  bridge-fungible-token/src/utils.sw
  bridge-fungible-token/tests/harness.rs
  bridge-fungible-token/tests/utils/builder.rs
  bridge-fungible-token/tests/utils/environment.rs
  bridge-fungible-token/tests/utils/ext_fuel_core.rs
  bridge-message-predicates/contract-message-receiver/Forc.lock
  bridge-message-predicates/contract-message-receiver/src/lib.sw
Labels: New Feature

#33 Improved test harness for BridgeFungibleToken contract
  README.md
  bridge-fungible-token/Cargo.lock
  bridge-fungible-token/Cargo.toml
  bridge-fungible-token/Forc.lock
  bridge-fungible-token/Forc.toml
  bridge-fungible-token/src/bridge_fungible_token.sw
  bridge-fungible-token/src/errors.sw
  bridge-fungible-token/src/utils.sw
  bridge-fungible-token/tests/harness.rs
  bridge-fungible-token/tests/utils/builder.rs
  bridge-fungible-token/tests/utils/environment.rs
Labels: Improvement, Testing

#37 Define deployment process docs and script
  README.md
  docs/deploy_docs.md
Labels: Documentation

#35 Opimization to multiplication operations.
  bridge-fungible-token/Forc.lock
  bridge-fungible-token/src/bridge_fungible_token.sw
  bridge-fungible-token/src/errors.sw
  bridge-fungible-token/src/utils.sw
Labels: Improvement
